name: Update China IP list and generate GeoIP2 database

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

  schedule: 
    - cron: "30 6 * * *"

jobs:
  build:
    name: Generate GeoIP2 database
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Create dist folder
      run: mkdir -p dist
    - name: Compile GeoIP conversion bin (Golang)
      run: /bin/bash ./build.sh

    - name: Obtain CN IP lists
      run: |
        #chinaIP
        curl -LR -o dist/china1.txt "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt"
        curl -LR -o dist/china2.txt "https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt"
        curl -LR -o dist/china-v6.txt "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt"
        
        #GFW
        curl -LR -o dist2/greatfire.txt "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/greatfire.txt"
        curl -LR -o dist2/gfw0.txt "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt"
        
        #Domestic-Domain
        curl -LR -o dist/domains.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf"
        curl -LR -o dist/apple.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf"
        curl -LR -o dist/google.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf"

    - name: Merge and IP lists and remove duplicates
      run: |
        awk 'FNR==1{print ""}{print}' dist/china+[1-9].txt > dist/v4.txt
        awk '!seen[$0]++' dist/v4.txt | sort -n > dist/china-v4.txt
        awk 'FNR==1{print ""}{print}' dist/chinav[1-9].txt > dist/china.txt
        awk '!seen[$0]++' dist/china.txt | grep -Ev "^#|^$" > dist/CN-ip-cidr.txt
        
        awk 'FNR==1{print ""}{print}' dist/*.txt > dist/merge2.txt
        awk '!seen[$0]++' dist/merge2.txt | sed "s/www.//p" > dist/gfw00.txt
        awk '!seen[$0]++' dist/gfw00.txt | grep -Ev "^#|^$" > dist/gfw.txt  

        
        awk 'FNR==1{print ""}{print}' dist/*.conf > dist/merge2.conf
        awk '!seen[$0]++' dist/merge2.conf | grep -Ev "^#|^$" > dist/domestic-domain.conf
        sed -i "s/^server=\/\(.*\)\/[^\/]*$/nameserver \/\1\/domestic/g;/^nameserver/!d" dist/domestic-domain.conf
        
        cat dist/CN-ip-cidr.txt | sed "s/^\(.*\)$/Whitelist-ip \1/g" > dist/Whitelist-ip.conf
        cat dist/gfw.txt | sed "s/^\(.*\)$/nameserver \/\1\/abroad/g" > dist/gfw-domain.conf
    - name: Generate GeoIP2 database
      run: |
        CURRENT_DIR=$(pwd)
        cd dist
        ./ipip2mmdb -s ./CN-ip-cidr.txt -d Country.mmdb
        cd $CURRENT_DIR
        
    - name: Push artifacts to release branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git fetch
        git checkout release
        
        git checkout --orphan release-orphan
        git rm -rf .
        
        cp -rf dist/CN-ip-cidr.txt ./
        cp -rf dist/gfw.txt ./
        cp -rf dist/Country.mmdb ./
        cp -rf dist/Whitelist-ip.conf ./
        cp -rf dist/domestic-domain.conf ./
        cp -rf dist/gfw-domain.conf ./
        
        git add Country.mmdb
        git add CN-ip-cidr.txt
        git add gfw.txt
        git add Whitelist-ip.conf
        git add domestic-domain.conf
        git add gfw-domain.conf
        
        git commit -am "Updated at $(date)"
        
        git branch -D release
        git branch -m release
            
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: release
        force: true
