name: Update ChinaIP-and-GFW database

on:
  workflow_dispatch:
  schedule: 
    - cron:  '30 6 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      
jobs:
  build:
    name: Generate GeoIP2 database
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
    - name: Create dist folder
      run: mkdir -p dist1
           mkdir -p dist2
           mkdir -p dist3
           mkdir -p dist4
           mkdir -p dist5
    - name: Compile GeoIP conversion bin (Golang)
      run: /bin/bash ./build.sh

    - name: Obtain CN IP lists
      run: |
        #chinaIP
        curl -LR -o dist/ChinaIPv4-1.txt "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt"
        curl -LR -o dist/ChinaIPv4-2.txt "https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt"
        curl -LR -o dist4/ChinaIPv4-3.txt "https://raw.githubusercontent.com/metowolf/iplist/master/data/country/CN.txt"
        curl -LR -o dist2/ChinaIPv6.txt "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt"
        
        #GFW
        curl -LR -o dist3/gfw1.txt "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/greatfire.txt"
        curl -LR -o dist3/gfw2.txt "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt"
        curl -LR -o dist3/gfw3.txt "https://raw.githubusercontent.com/RodmanWang/ChinaIP-and-GFW/main/patch/gfw-custom.txt"
        
        #Domestic-Domain
        curl -LR -o dist/domains.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf"
        ##curl -LR -o dist/apple.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf"
        ##curl -LR -o dist/google.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf"
        curl -LR -o dist/domestic--custom.conf "https://raw.githubusercontent.com/RodmanWang/ChinaIP-and-GFW/main/patch/domestic-custom.conf"
        
    - name: Merge and IP lists and remove duplicates
      run: |
        awk 'FNR==1{print ""}{print}' dist/*.txt > dist/ChinaIP.txt
        awk '!seen[$0]++' dist/ChinaIP.txt | sort -n | grep -Ev "^#|^$" > dist/ChinaIPv4v1.txt
        
        cp -f dist/ChinaIPv4-1.txt  dist4/ChinaIPv4-1.txt
        cp -f dist/ChinaIPv4-2.txt  dist4/ChinaIPv4-2.txt
        awk 'FNR==1{print ""}{print}' dist4/*.txt > dist4/ChinaIPv2.txt
        awk '!seen[$0]++' dist4/ChinaIPv2.txt | sort -n | grep -Ev "^#|^$" > dist2/ChinaIPv4v2.txt

        cp -f dist/ChinaIPv4v1.txt  dist5/ChinaIPv4-1.txt
        cp -f dist2/ChinaIPv6.txt  dist5/ChinaIPv6.txt
        awk 'FNR==1{print ""}{print}' dist5/*.txt | grep -Ev "^#|^$"  > dist/China-IPv1.txt
        awk 'FNR==1{print ""}{print}' dist2/*.txt | grep -Ev "^#|^$"  > dist/China-IPv2.txt
                
        awk 'FNR==1{print ""}{print}' dist3/*.txt > dist3/gfw0.txt
        awk '!seen[$0]++' dist3/gfw0.txt | sed "s/^www\.//p" > dist3/gfw00.txt
        awk '!seen[$0]++' dist3/gfw00.txt | grep -Ev "^#|^$" > dist/GFW.txt  
        
        awk 'FNR==1{print ""}{print}' dist/*.conf > dist/china1.conf
        awk '!seen[$0]++' dist/china1.conf | grep -Ev "^#|^$" > dist/China-domain.conf
        sed -i "s/^server=\/\(.*\)\/[^\/]*$/nameserver \/\1\/domestic/g;/^nameserver/!d" dist/China-domain.conf
        
        cat dist/China-IPv1.txt | sed "s/^\(.*\)$/Whitelist-ip \1/g" > dist/Whitelist-ipv1.conf
        cat dist/China-IPv2.txt | sed "s/^\(.*\)$/Whitelist-ip \1/g" > dist/Whitelist-ipv2.conf
        cat dist/GFW.txt | sed "s/^\(.*\)$/nameserver \/\1\/abroad/g" > dist/GFW.conf
        
    - name: Generate GeoIP2 database
      run: |
        CURRENT_DIR=$(pwd)
        cd dist
        ./ipip2mmdb -s ./China-IPv2.txt -d Country.mmdb
        cd $CURRENT_DIR
        
    - name: Push artifacts to release branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git fetch
        git checkout release
        
        git checkout --orphan release-orphan
        git rm -rf .
        
        cp -rf dist/ChinaIPv4v1.txt ./
        cp -rf dist2/ChinaIPv4v2.txt ./
        cp -rf dist2/ChinaIPv6.txt ./
        cp -rf dist/GFW.txt ./
        cp -rf dist/Country.mmdb ./
        cp -rf dist/China-domain.conf ./
        cp -rf dist/Whitelist-ipv1.conf  ./
        cp -rf dist/Whitelist-ipv2.conf ./
        cp -rf dist/GFW.conf ./
        
        git add Country.mmdb
        git add ChinaIPv4v1.txt
        git add ChinaIPv4v2.txt
        git add ChinaIPv6.txt
        git add GFW.txt
        git add Whitelist-ipv1.conf
        git add Whitelist-ipv2.conf
        git add China-domain.conf
        git add GFW.conf
        
        git commit -m "update : $(TZ=UTC-8 date "+%Y-%m-%d %H:%M:%S")"
        git branch -D release
        git branch -m release
            
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: release
        force: true
